OrdererOrgs: # organisation to manage orderer nodes
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
      - Hostname: orderer2

PeerOrgs: # organisation managing peers 
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 2 # two peers
    Users:
      Count: 1
  
  - Name: Org2
    Domain: org2.example.com
    Template: 
      Count: 2
    Users:
      Count: 1
